# Generated by Django 6.0 on 2025-12-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('token_number', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('called', 'Called'), ('done', 'Done')], default='pending', max_length=10)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
